# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'CS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS
  pod 'RxSwift', '6.7.1'
  pod 'RxCocoa', '6.7.1'	
  pod 'ReactorKit'
  pod 'SnapKit', '~> 5.7.0'
  pod 'RealmSwift'
end